print("Sirinda Wisetchat")
print("      *      ")
print("    *   *    ")
print("  *       *  ")
print("*************")
print("*           *")
print("*           *")
print("*   *****   *")
print("*   *   *   *")
print("*****   *****")
input()
